<?php
/** @var \Virementmaitrise\HyvaPayment\Block\Checkout\Success $block */
?>
<?php if ($block->getPaymentStatus() === 'payment_created'): ?>
    <div class="fintecture-alert fintecture-alert-success">
        <img src="<?php echo $block->getViewFileUrl('Virementmaitrise_HyvaPayment::images/success.svg'); ?>">
        <p><?php echo __('Your payment with Virement Maitrisé has been successfully processed!'); ?></p>
    </div>
<?php elseif ($block->getPaymentStatus() === 'payment_pending'): ?>
    <div class="fintecture-alert fintecture-alert-info">
        <img src="<?php echo $block->getViewFileUrl('Virementmaitrise_HyvaPayment::images/info.svg'); ?>">
        <p><?php echo __('Your payment with Virement Maitrisé is currently being processed by your bank. You can track the status of your payment using the link provided in the confirmation email.'); ?></p>
    </div>
<?php endif; ?>