<?php
/** @var \Virementmaitrise\HyvaPayment\Block\QrCode $block */
?>
<div style="text-align: center;">
    <?php
    if ($block->getData('confirm')) {
        ?>
        <h2><?= $block->escapeHtml(__('Order validated')) ?></h2>

        <p>
            <?= $block->escapeHtml(__(
                'If the payment has been made, then the order will be validated in a few moments.'
            )) ?>
        </p>

        <p>
            <b>
                <?= $block->escapeHtml($block->getData('amount')) ?>
                <?= $block->escapeHtml($block->getData('currency')) ?>
            </b>
        </p>
        <p><?= $block->escapeHtml($block->getData('reference')) ?></p>
        <p><?= $block->escapeHtml($block->getData('sessionId')) ?></p>

        <a href="<?= $block->escapeUrl($block->getData('baseUrl')) ?>"
           class="action primary"
           style="margin-top: 20px;">
            <?= $block->escapeHtml(__('Return to the homepage')) ?>
        </a>
        <?php
    } else {
        ?>
        <h2><?= $block->escapeHtml(__('Scan this QR Code to pay with Virement Maitrisé')) ?></h2>

        <img src="<?= $block->escapeUrl($block->getData('qrCode')) ?>">

        <p>
            <b>
                <?= $block->escapeHtml($block->getData('amount')) ?>
                <?= $block->escapeHtml($block->getData('currency')) ?>
            </b>
        </p>
        <p><?= $block->escapeHtml($block->getData('reference')) ?></p>
        <p><?= $block->escapeHtml($block->getData('sessionId')) ?></p>

        <a href="<?= $block->escapeUrl($block->getData('confirmUrl')) ?>"
           title="<?= $block->escapeHtmlAttr(__('Continue')) ?>"
           class="action primary"
           style="margin-top: 20px;">
            <?= $block->escapeHtml(__('Continue')) ?>
        </a>
        <?php
    }
    ?>

    <div style="margin-top: 20px; display: flex; flex-direction: column; align-items: center;
                justify-content: center; gap: 8px;">
        <span style="text-transform: uppercase; color: #0B1643; font-weight: bold; font-size: 0.8em;">
            <?= $block->escapeHtml(__('Secured connection to your bank by')) ?>
        </span>
        <img src="<?= $block->escapeUrl(
            $block->getViewFileUrl('Virementmaitrise_HyvaPayment::images/virementmaitrise.svg')
        ) ?>"
             alt="Virement Maitrisé"
             style="height: 25px;">
    </div>
</div>