<?php
/** @var \Virementmaitrise\HyvaPayment\Block\Send $block */
?>
<div style="text-align: center;">
    <?php
    if ($block->getData('step') !== 2) {
        ?>
        <h2><?= $block->escapeHtml(__('Choose how to send your payment link')) ?></h2>

        <div style="display: flex; flex-direction: row; align-items: center; justify-content: center;
                    gap: 10px;">
            <a href="<?= $block->escapeUrl($block->getData('sendByEmailUrl')) ?>" class="action primary">
                <?= $block->escapeHtml(__('Send by Email')) ?>
            </a>
            <a href="<?= $block->escapeUrl($block->getData('sendBySMSUrl')) ?>" class="action primary">
                <?= $block->escapeHtml(__('Send by SMS')) ?>
            </a>
        </div>
        <?php
    } else {
        ?>
        <h2><?= $block->escapeHtml(__('Your payment link has been sent successfully')) ?></h2>

        <img src="<?= $block->escapeUrl($block->getData('qrCode')) ?>">

        <p>
            <b>
                <?= $block->escapeHtml($block->getData('amount')) ?>
                <?= $block->escapeHtml($block->getData('currency')) ?>
            </b>
        </p>
        <p><?= $block->escapeHtml($block->getData('reference')) ?></p>
        <p><?= $block->escapeHtml($block->getData('sessionId')) ?></p>

        <a href="<?= $block->escapeUrl($block->getData('baseUrl')) ?>"
           class="action primary"
           style="margin-top: 20px;">
            <?= $block->escapeHtml(__('Return to the homepage')) ?>
        </a>
        <?php
    }
    ?>

    <div style="margin-top: 20px; display: flex; flex-direction: column; align-items: center;
                justify-content: center; gap: 8px;">
        <span style="text-transform: uppercase; color: #0B1643; font-weight: bold; font-size: 0.8em;">
            <?= $block->escapeHtml(__('Secured connection to your bank by')) ?>
        </span>
        <img src="<?= $block->escapeUrl(
            $block->getViewFileUrl('Virementmaitrise_HyvaPayment::images/virementmaitrise.svg')
        ) ?>"
             alt="Virement Maitrisé"
             style="height: 25px;">
    </div>
</div>