<?php
    /** @var \Virementmaitrise\HyvaPayment\Magewire\Checkout\Payment\Fintecture $magewire */
    /** @var \Magento\Framework\View\Element\Template $block */
    $locale = $block->getLocale();
    $design = $magewire->getCheckoutDesign();
?>

<div id="payment-method-fintecture" data-design="<?= $block->escapeHtmlAttr($design) ?>">
    <?php if ($design === 'it'): ?>
        <img src="<?= $block->escapeUrl($magewire->getAssetsUrl()) ?>/checkout/it_payment_method_description_<?= $block->escapeHtmlAttr($magewire->getCurrentLang()) ?>_soc-gen.svg"/>
    <?php elseif ($design === 'ist_long'): ?>
        <img src="<?= $block->escapeUrl($magewire->getAssetsUrl()) ?>/checkout/it-st_payment_method_description_<?= $block->escapeHtmlAttr($magewire->getCurrentLang()) ?>_soc-gen.svg"/>
    <?php endif ?>
</div>

